var name = "spring";

var letter = `dnfkjwebrhvha${name}

  hlkwhnkwkhjbgkwsjhfioawu3iosajejghsdvcweftjagsdysgvfnshdgfygsdfjqvnwn3iuryuahdkasndjfbrjhsagravu3yviuhgkjhsdklkwhnkwkhjbgkwsjhfioawu3iosajejghsdvcweftjagsdysgvfnshdgfygsdfjqvnwn3iuryuahdkasndjfbrjhsagravu3yviuhgkjhsdklkwhnkwkhjbgkwsjhf${name}ioawu3iosajejghsdvcweftjagsdysgvfnshdgfygsdfjqvnwn3iuryuahdkasndjfbrjhsagravu3${name}iuhgkjhsdklkwhnkwkhjbgkwsjhfioawu3iosajejghsdvcweftjagsdysgvfnshdgfygsdfjqvnwn3iuryuahdkasndjfbrjhsagravu3yviuhgkjhsdk`;
console.log(letter);
